#!/bin/bash
# Make vespagram at given azimuth for given beam file
#if [ $# != 5 ] || [ $# != 5 ]; then
if [ $# == 0 ]; then
   echo "USAGE: ./vespagram BEAMFILE baz t_start t_end"
   echo "                    OR"
   echo "USAGE: ./vespagram BEAMFILE baz t_start t_end maxfile"
   echo "       where maxfile gives coordinates of local maxima"
   echo "       generated by xh_beammax"
   echo "This version is for z component vespagrams with P wave at 200 seconds"
   exit
fi

vesp_file=${1/.beam/_vesp}

if [ ! -d $vesp_file ]; then mkdir $vesp_file; fi

cwd=$(pwd)
num=$(printf "%04d" $2)
echo "number: "$num
file=$vesp_file/vespagram_$num
scale=X6.5i/3.5i
region=$3/$4/-4/4
cpt_dir=$SRC/beamform_plot/custom_cpt

if [ ! -e $cwd/describe ]; then
   echo "baz.dat not found computing back-azimuth"
   xh_beamdescribe $1 > $cwd/describe
fi
alat=$(grep array_centroid_lat $cwd/describe | awk '{print $2}')
alon=$(grep array_centroid_lon $cwd/describe | awk '{print $2}')
elat=$(grep event_lat $cwd/describe | awk '{print $2}')
elon=$(grep event_lon $cwd/describe | awk '{print $2}')
baz=$(vincenty_inverse $elat $elon $alat $alon | awk '{print $2}')
gcarc=$(vincenty_inverse $elat $elon $alat $alon | awk '{print $3}')
evdp=$(grep event_depth $cwd/describe | awk '{print $2}')

lin_max=$(grep dat1 $cwd/describe | awk '{print $4}')
lin_max=$(echo "$lin_max*0.8" | bc -l)
lin_min=$(echo "-1*$lin_max" | bc -l)

root_max=$(grep dat2 $cwd/describe | awk '{print $4}')
root_max=$(echo "$root_max*0.05" | bc -l)
sem_max=$(grep dat3 $cwd/describe | awk '{print $4}')
sem_max=$(echo "$sem_max*0.8" | bc -l)

gmt gmtset COLOR_FOREGROUND=black

gmt makecpt -N -M -Chot -T0/1/0.01 -D -I -Z > $vesp_file/cmap_${2}.cpt

xh_beamvesp $1 $2 | awk '{print $1,$3,$5}' > $vesp_file/vesp_${2}.dat

gmt surface $vesp_file/vesp_${2}.dat -R$region -G$vesp_file/tmp_${2}.grd -I0.2/0.2 -Ll0

gmt grdimage $vesp_file/tmp_${2}.grd -R$region -J$scale -BSWne+t"baz:$2, gcarc:$gcarc, evdp:$evdp"  \
                    -Bxa50f10+l"Time (s)" -Bxg50 -Byg1 -Bya1f0.2+l"Slowness w.r.t P (s/deg)" \
                    -C$vesp_file/cmap_${2}.cpt -nl -K -P -Y5i > $file.ps

if [ $# == 5 ]; then
   awk -v baz=$2 '{if($1==baz) print $3,$2}' $5 | \
   gmt psxy -J$scale -R$region -Sx2.25c -W1p,green -K -O -P>> $file.ps
fi

gmt grdcontour $vesp_file/tmp_${2}.grd -R$region -J$scale  \
                    -C$SRC/beamform_plot/cont_int -K -O -P >> $file.ps


#rm vespagram/cmap_${2}.cpt
rm vespagram/vesp_${2}.dat
rm vespagram/tmp_${2}.grd 

